### ISSUE TITLE
always replace $? with exit code

### ISSUE THREAD

**Issue by PaulicStudios** [JonasGoetz01/42-minishell#104]
`test$?asd` should expand to test0asd

**Comment by PaulicStudios** [comment]
vidus krasserer programierer als jgotz

**Comment by JonasGoetz01** [comment]
> vidus krasserer programierer als jgotz (hat FIndus geschrieben)

halte ich für ein Gerücht. (Soll erstmal pushswap fertig machen :))

**Comment by JonasGoetz01** [comment]
solle in #121 gemacht sein
