### ISSUE TITLE
< out1 < out3 wc

### ISSUE THREAD

**Issue by PaulicStudios** [JonasGoetz01/42-minishell#112]
should parse fine as a valid input

**Comment by PaulicStudios** [comment]
also happens in #109

**Comment by JonasGoetz01** [comment]
Wie soll das funktionieren? Ich dachte, dass ein redirect operator, wenn er als erstes kommt die file direct hinten dran hat und als nächstes ein Command kommen muss. Hier ist bei out1 nur eine Outfile. Wie soll das dann am Ende richtig aussehen?
