### ISSUE TITLE
echo -n test1		test2 | test1 and test2 are not seperate tokens

### ISSUE THREAD

**Issue by PaulicStudios** [JonasGoetz01/42-minishell#215]
Output now:
```
Type: 0, Value: echo Prio: 1
Type: 0, Value: -n Prio: 1
Type: 15, Value:   Prio: 1
Type: 0, Value: test1           test2 Prio: 1
```
Expected Output:
Two seperate tokens with a space in between

**Comment by JonasGoetz01** [comment]
![CleanShot 2024-04-29 at 22 08 22@2x](https://github.com/JonasGoetz01/42-minishell/assets/65551807/1f6e71ae-5e9c-484a-a23e-221b1b21778a)

kann ich leider nicht nachstellen

**Comment by PaulicStudios** [comment]
`echo test1             test2`
