### ISSUE TITLE
/bin/echo '' "" | only one whitespace word token

### ISSUE THREAD

**Issue by PaulicStudios** [JonasGoetz01/42-minishell#218]
Tokens now:
```
Type: 0, Value: /bin/echo Prio: 1
Type: 0, Value:  Prio: 1
```
There should be two whitespace tokens

**Comment by JonasGoetz01** [comment]
![CleanShot 2024-04-29 at 22 10 41@2x](https://github.com/JonasGoetz01/42-minishell/assets/65551807/8823d6d5-7562-4838-b525-5b53e00912dc)

bash macht nur einen
