### ISSUE TITLE
echo with argument that gets expanded to empty sting in quotes must add space 

### ISSUE THREAD

**Issue by JonasGoetz01** [JonasGoetz01/42-minishell#229]
currently it gets converted to a ampersand in quotes. 
@PaulicStudios maybe echo needs to be fixed too.

**Comment by PaulicStudios** [comment]
an echo ändern wir nichts mehr. Das muss wenn dann davor in org_tokens oder bei dir gefixt werden

**Comment by PaulicStudios** [comment]
Das was bei mir nicht funktioniert hat ist folgendes wenn Test empty ist:
`echo $Test | wc`
da kommt Syntax error raus

**Comment by JonasGoetz01** [comment]
geht bei mir jetzt alles
