### ISSUE TITLE
echo 1 | >tmp_out should not be invalid

### ISSUE THREAD

**Issue by JonasGoetz01** [JonasGoetz01/42-minishell#233]

**Comment by PaulicStudios** [comment]
'<<' und '>>' als input sollten auch invalid sein

**Comment by PaulicStudios** [comment]
`/bin/echo $"42$"` should not be invalid

**Comment by PaulicStudios** [comment]
`/bin/echo "$ "` should not be invalid syntax

**Comment by PaulicStudios** [comment]
`echo "$/ $/"` should not be invalid syntax

**Comment by PaulicStudios** [comment]
`ls|cat Makefile|<wc -l` should not be invalid
