### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by PaulicStudios** [JonasGoetz01/42-minishell#239]
Inputs die Invalid Syntax returnen sollten:
`<<`
`>>`
`>`
`<`
`>>echo>>`
`>echo>`
`echo >`
`<echo<`
`/bin/cat <Makefile >`

**Comment by JonasGoetz01** [comment]
@PaulicStudios  Das bringt mir so nichts. Können wir da irgendwie eine Logik dahinter feststellen? Ich brauche eine Tabelle, was für die einzelnen Operatoren erlaubt ist.

z.B.:
> -> invalid
> out -> invalid
cmd > out -> valid
cmd args > out -> valid
> out cmd -> valid --> cmd > out
> out cmd args -> valid --> cmd args > out
cmd > -> invalid
cmd args > -> invalid

| > out -> valid
anderer operator -> invalid
(was ich an Logik denke)
ein > muss vorher eine beliebige Anzahl Wörter oder eine Pipe haben und danach ein Wort

< in -> valid
cmd < in -> valid
cmd args < in -> valid
cmd < -> invalid
cmd args < -> invalid
cmd | < in -> valid

(sieht aus als müsste nach einem < ein Input file stehen und davor eine Pipe oder ein cmd)

>> ist denke ich identisch zu >

<< musst du am besten ergänzen, da habe ich nicht so wirklich Plan von

**Comment by PaulicStudios** [comment]
Ich kenn da auch noch keine Logic dahinter. Das war halt einfach mal das was so beim testen rauskam. Aber ich kann mir das mal genauer anschauen
