### ISSUE TITLE
echo $/ $/ missing space token

### ISSUE THREAD

**Issue by PaulicStudios** [JonasGoetz01/42-minishell#251]
missing space token in between of the two dollars
has nothing to do with not handling backspaces

**Comment by JonasGoetz01** [comment]
![CleanShot 2024-05-03 at 00 19 04@2x](https://github.com/JonasGoetz01/42-minishell/assets/65551807/6ec14aa0-88a0-453d-87af-c1c57346829f)

should be fine now
