### ISSUE TITLE
command and argument fuse together

### ISSUE THREAD

**Issue by JonasGoetz01** [JonasGoetz01/42-minishell#254]
![CleanShot 2024-05-02 at 16 16 17@2x](https://github.com/JonasGoetz01/42-minishell/assets/65551807/527a51e0-7b20-4af9-a181-8a252532a451)

kein plan was da passiert

**Comment by JonasGoetz01** [comment]
input: echo $"42 $" | cat -e

passiert nicht, wenn ich den quotes kein $ ist. 
Aber von meinen Token her sollte das glaube ich passen

wenn ich zwischen cat und -e zwei spaces mache klappt es plötzlich auch wieder

**Comment by PaulicStudios** [comment]
Da fehlt ein space token zeischen cmd und arg. Deswegen wird der gemerged

**Comment by PaulicStudios** [comment]
Jo, die Logic bei mir geht halt so wenn zwischen zwei Word tokens kein Space ist werden die zusammengemerged

**Comment by JonasGoetz01** [comment]
> Jo, die Logic bei mir geht halt so wenn zwischen zwei Word tokens kein Space ist werden die zusammengemerged

hmm okay. Seit wann das?

**Comment by PaulicStudios** [comment]
Seit 1,5 Wochen glaub ich. Das fixt halt alles wie zum Bsp. 'e"ch"o' oder 'echo "hallo""welt"'

**Comment by PaulicStudios** [comment]
Das war als ich dir mal gesagt hab dass ich die remove unused spaces auskommentiert hab
