### ISSUE TITLE
ls|cat Makefile|cat<<asd>out

### ISSUE THREAD

**Issue by PaulicStudios** [JonasGoetz01/42-minishell#287]

**Comment by JonasGoetz01** [comment]
<img width="297" alt="image" src="https://github.com/JonasGoetz01/42-minishell/assets/65551807/c58e757d-aafc-4c6a-9ef2-7b6c3deb0f67">

kann da keinen Fehler im AST erkenne. Da war ein Fehler, dass die Tabs nur für das erste Element auf jedem Layer geprinted.
