### ISSUE TITLE
$something are two different tokens

### ISSUE THREAD

**Issue by PaulicStudios** [JonasGoetz01/42-minishell#34]
Input: echo $HOME
Sollte nicht $HOME ein Token sein? Dann würde die Expander Logic funktionieren. Wenn du das gewollt geändert hast kann ich die Expander Funktion anpassen
<img width="219" alt="Screen Shot 2024-04-13 at 10 52 27 PM" src="https://github.com/JonasGoetz01/42-minishell/assets/61714149/708f7d2b-b2cf-422d-919e-f56068aa485e">

**Comment by JonasGoetz01** [comment]
already fixed
